systemsomicslab/MsdialWorkbench

src/MSDIAL5/MsdialGuiApp/View/Help/HelpAboutDialog.xaml
=> Change contact information to the development team's email address.

src/MSDIAL5/MsdialGuiApp/Model/Search/CompoundSearchModel.cs
If there is no library, compound search was failed.
=> Fix a bug of CompoundSearchModel.

src/MSFINDER/MSFINDER/Utility/ExportUtility.cs
=> #103 Change MS-FINDER export format from column-wide to row-wide.

src/Common/CommonStandard/Algorithm/Function/MoleculerNetworking.cs, src/Common/CommonStandard/DataObj/NodeEdge/MolecularNetworkObj.cs
review my moleculer networking source codes.
=> added moleculer networking function in common standards.

src/MSDIAL4/MsDial/Properties/Resources.resx, src/MSDIAL4/MsDial/Vesrion update/VersionUpdateNotificationService.cs, src/MSDIAL5/MsdialGuiApp/Model/Notification/VersionUpdateNotificationService.cs, src/MSDIAL5/MsdialGuiApp/Properties/Resources.resx, src/MSFINDER/MSFINDER/Properties/Resources.resx, src/MSFINDER/MSFINDER/Version update/VersionUpdateNotificationService.cs
This PR will migrate the version notification system from our own (RIKEN) server to GitHub.
=> 147 release distribution with GitHub releases

src/MSFINDER/MSFINDER/Utility/ExportUtility.cs
=> Change spectrum export from profile to centroid in MSP files from MSFinder

src/MSDIAL5/MsdialCore/Algorithm/PeakSpottingCore.cs
=> Update MS/MS Spectrum Selection Criteria to Require Minimum One Peak

src/Common/CommonStandard/Algorithm/Function/MoleculerNetworking.cs
To accept "null" formula in MN
=> Mn null accept

src/Common/CommonStandard/Parser/TextLibraryParser.cs, tests/Common/CommonStandardTests/CommonStandardTests.csproj, tests/Common/CommonStandardTests/Parser/TextLibraryParserTests.cs, tests/Common/CommonStandardTests/Resources/Parser/txt_with_blank_end_line.txt
Description:
This pull request addresses an issue where the program would fail when the last line of a text file was empty. The following changes were made:
Bug Fix: Corrected the handling of files with an empty last line, ensuring that the program no longer encounters errors in this scenario.
Test Added: Introduced a test case specifically for verifying the correct behavior when the last line is empty. This helps to prevent regressions in the future.
=> Fix handling of empty last line in text files

tests/MSDIAL5/MsdialCoreTestApp/Process/DimsProcess.cs, tests/MSDIAL5/MsdialCoreTestApp/Process/GcmsProcess.cs, tests/MSDIAL5/MsdialCoreTestApp/Process/ImmsProcess.cs, tests/MSDIAL5/MsdialCoreTestApp/Process/LcimmsProcess.cs, tests/MSDIAL5/MsdialCoreTestApp/Properties/launchSettings.json
fix console gapfill func for GC by adding ProviderFactory
=> fix console gapfill func for GC

src/MSDIAL5/MsdialGuiApp/Model/Setting/DataBaseSettingModel.cs
Add ErrorMessageBox before the program crashes if the text library is bad
=> Add ErrorMessageBox on TextLibraryReader

src/Common/CommonStandard/Algorithm/Scoring/MsScanMatching.cs, src/Common/CommonStandard/Lipidomics/Lipidomics.cs, src/Common/CommonStandard/Lipidomics/MsmsCharacterization.cs, src/Common/CommonStandard/Resources/LbmQueries.txt
Add PC[H+HCO3]- annotation metnods
and fix annotation level 3 on CID
=> Add PC[H+HCO3]- annotation metnods

src/MSDIAL5/MsdialCore/Algorithm/Alignment/PeakAligner3D.cs, src/MSDIAL5/MsdialGuiApp/Model/Setting/MobilitySettingModel.cs, src/MSDIAL5/MsdialGuiApp/Properties/Resources.Designer.cs, src/MSDIAL5/MsdialGuiApp/Properties/Resources.resx, src/MSDIAL5/MsdialLcImMsApi/Algorithm/Alignment/LcimmsGapFiller.cs, src/MSDIAL5/MsdialLcImMsApi/Algorithm/Alignment/LcimmsPeakJoiner.cs
Refactored LC-IM-MS Alignment Algorithm and Fixed CCS Calculation Bug
This pull request addresses key issues and improvements in the LC-IM-MS workflow:
* Alignment Algorithm Update
Refactored the alignment logic specific to LC-IM-MS to improve accuracy and maintainability.
* CCS Calculation Bug Fix
Fixed a bug in the calculation of collision cross section (CCS) values, ensuring correct results during LC-IM-MS processing.
=> Refactored LC-IM-MS Alignment Algorithm and Fixed CCS Calculation Bug

src/Common/CommonStandard/Lipidomics/MsmsCharacterization.cs, src/Common/CommonStandard/Resources/LbmQueries.txt, tests/Common/CommonStandardTests/Lipidomics/MsmsCharacterizationTests.cs
Add [M+HCO3]- annotation method (EtherPC, LPC, EtherLPC, OxPC, EtherOxPC, SM) and tests
=> Add hco3  adduct annotation method

src/MSDIAL5/MsdialGuiApp/Model/Chart/AlignmentEicModel.cs, src/MSDIAL5/MsdialGuiApp/Model/DataObj/AlignedChromatograms.cs, src/MSDIAL5/MsdialGuiApp/Model/Information/MatchResultCandidatesModel.cs, src/MSDIAL5/MsdialGuiApp/Model/Loader/AlignmentEicLoader.cs, src/MSDIAL5/MsdialGuiApp/View/PeakCuration/AlignedPeakCorrectionWinLegacy.xaml.cs, src/MSDIAL5/MsdialGuiApp/ViewModel/PeakCuration/AlignedChromatogramModificationViewModelLegacy.cs, tests/MSDIAL5/MsdialGuiAppTests/Utility/ObservableExtensionsTests.cs
Code cleanup, performance optimization, and bug fixes.  
This PR refactors reactive streams for improved performance, enhances code maintainability, and fixes potential null handling issues while adding test coverage for reliability.  
- **Reactive Streams**: Introduced "hot" observables (`spotChromatogramsHot`, `hotContainerOx`) and added `.Replay(1).RefCount()` for shared subscriptions and caching.  
- **AlignmentEicModel.cs**: Replaced `spotChromatograms` with `spotChromatogramsHot` for consistency and performance.  
- **MatchResultCandidatesModel.cs**: Refactored constructor to use "hot" observables and optimized property initialization.  
- **AlignedPeakCorrectionWinLegacy.xaml.cs**: Encapsulated file properties into a new `FileProp` class for better organization.  
- …
=> Fixed Unnecessary Chromatogram Loading and Improved Reactive Stream Handling in Result View

src/MSDIAL4/MolecularFormulaFinderStandard/File manage/RawDataParcer.cs, src/MSFINDER/MSFINDER/Utility/RefreshUtility.cs, src/MSFINDER/MSFINDER/ViewModel/CreateSpectrumFileVM.cs
Fix file writer of MSBANK format.
Fix raw data parsing.
=> Independent msfinder bug fix

src/MSFINDER/MsfinderCommonStandard/Process/StructureFinder.cs
fixed file generator in msfinder
=> fixed file generator in msfinder

src/MSDIAL5/MsdialCore/MSDec/MSDecHandler.cs
fixed splash calculator in ms-dial
=> fixed splash calculator in ms-dial

src/MSDIAL5/MsdialCore/DataObj/AnnotatedMSDecResult.cs, src/MSDIAL5/MsdialGcMsApi/Algorithm/Alignment/GcmsPeakJoiner.cs
=> Update gcms alignment process

tests/Common/ChartDrawingTests/ChartDrawingTests.csproj, tests/Common/CommonMVVMTests/CommonMVVMTests.csproj, tests/Common/CommonSourceGeneratorTests/CommonSourceGeneratorTests.csproj, tests/Common/CommonStandardTestHelper/CommonStandardTestHelper.csproj, tests/Common/CommonStandardTests/CommonStandardTests.csproj, tests/MSDIAL4/MonaRestApiTests/MonaRestApiTests.csproj, tests/MSDIAL4/StatisticsTests/StatisticsTests.csproj, tests/MSDIAL5/MsdialCoreTestHelper/MsdialCoreTestHelper.csproj, tests/MSDIAL5/MsdialCoreTests/MsdialCoreTests.csproj, tests/MSDIAL5/MsdialDimsCoreTests/MsdialDimsCoreTests.csproj, tests/MSDIAL5/MsdialGcMsApiTests/MsdialGcMsApiTests.csproj, tests/MSDIAL5/MsdialGuiAppTests/MsdialGuiAppTests.csproj, tests/MSDIAL5/MsdialImmsCoreTests/MsdialImmsCoreTests.csproj, tests/MSDIAL5/MsdialIntegrateTests/MsdialIntegrateTests.csproj, tests/MSDIAL5/MsdialLcImMsApiTests/MsdialLcImMsApiTests.csproj, tests/MSDIAL5/MsdialLcMsApiTests/MsdialLcMsApiTests.csproj
=> Update MSTest packages

src/MSDIAL5/MsdialGuiApp/View/Setting/DatasetFileSettingView.xaml
Enhancement of user interface elements and feedback mechanisms.
This pull request updates the tooltip for a button and introduces new UI elements to improve user interaction. 
- **DatasetFileSettingView.xaml**: Updated tooltip content to remove specific format mention.
- **DatasetFileSettingView.xaml**: Added a `Viewbox` with a `TextBlock` that prompts users to select files or drag and drop when no files are present.
=> Add file selection instruction

src/MSDIAL5/MsdialCore/DataObj/DataBaseStorage.cs, src/MSDIAL5/MsdialGcMsApi/Algorithm/Alignment/GcmsAlignmentProcessFactory.cs, src/MSDIAL5/MsdialGuiApp/Model/Setting/MethodSettingModel.cs, tests/MSDIAL5/MsdialCoreTestApp/Process/DimsProcess.cs, tests/MSDIAL5/MsdialCoreTestApp/Process/GcmsProcess.cs, tests/MSDIAL5/MsdialCoreTestApp/Process/ImmsProcess.cs, tests/MSDIAL5/MsdialCoreTestApp/Process/LcimmsProcess.cs, tests/MSDIAL5/MsdialCoreTestApp/Process/LcmsProcess.cs, tests/MSDIAL5/MsdialCoreTestApp/Process/MaldiMsProcessTest.cs
This pull request fixes a bug specific to EAD lipidomics projects where the EAD annotation process failed to execute during the initial analysis.
* Ensures that the annotation logic is correctly triggered for EAD-specific workflows during the first run.
=> Fixed Bug Where EAD Annotation Did Not Run in Initial Analysis of EAD Lipidomics Project

src/Common/CommonMVVM/Common/DisposableModelBase.cs, src/MSDIAL5/MsdialDimsCore/Parameter/DimsProviderFactoryParameter.cs, src/MSDIAL5/MsdialDimsCore/Parameter/MsdialDimsParameter.cs, src/MSDIAL5/MsdialGuiApp/Model/Imaging/IWholeImageResultModel.cs, src/MSDIAL5/MsdialGuiApp/Model/Imaging/IntensityImageModel.cs, src/MSDIAL5/MsdialGuiApp/Model/Imaging/SaveImagesModel.cs, src/MSDIAL5/MsdialGuiApp/Model/ImagingDims/ImagingDimsImageModel.cs, src/MSDIAL5/MsdialGuiApp/Model/ImagingDims/ImagingDimsMethodModel.cs, src/MSDIAL5/MsdialGuiApp/Model/ImagingDims/WholeImageResultModel.cs, src/MSDIAL5/MsdialGuiApp/Model/ImagingImms/ImagingImmsImageModel.cs, src/MSDIAL5/MsdialGuiApp/Model/ImagingImms/ImagingImmsMethodModel.cs, src/MSDIAL5/MsdialGuiApp/Model/ImagingImms/SaveImagesModel.cs, src/MSDIAL5/MsdialGuiApp/Model/ImagingImms/WholeImageResultModel.cs, src/MSDIAL5/MsdialGuiApp/Model/Setting/DatasetParameterSettingModel.cs, src/MSDIAL5/MsdialGuiApp/Model/Setting/MethodSettingModelFactory.cs, src/MSDIAL5/MsdialGuiApp/View/Core/MainWindow.xaml, src/MSDIAL5/MsdialGuiApp/View/ImagingDims/DimsImagingRibbon.xaml, src/MSDIAL5/MsdialGuiApp/View/ImagingDims/DimsImagingRibbon.xaml.cs, src/MSDIAL5/MsdialGuiApp/View/ImagingDims/ImagingMainView.xaml, src/MSDIAL5/MsdialGuiApp/View/ImagingDims/ImagingMainView.xaml.cs, src/MSDIAL5/MsdialGuiApp/View/ImagingImms/ImagingMainView.xaml, src/MSDIAL5/MsdialGuiApp/View/Setting/DataCollectionSettingView.xaml, src/MSDIAL5/MsdialGuiApp/View/Setting/DatasetParameterSettingView.xaml, src/MSDIAL5/MsdialGuiApp/ViewModel/Core/DatasetViewModel.cs, src/MSDIAL5/MsdialGuiApp/ViewModel/Imaging/SaveImagesViewModel.cs, src/MSDIAL5/MsdialGuiApp/ViewModel/ImagingDims/ImagingDimsImageViewModel.cs, src/MSDIAL5/MsdialGuiApp/ViewModel/ImagingDims/ImagingDimsMainViewModel.cs, src/MSDIAL5/MsdialGuiApp/ViewModel/ImagingDims/WholeImageResultViewModel.cs, src/MSDIAL5/MsdialGuiApp/ViewModel/ImagingImms/ImagingImmsImageViewModel.cs, src/MSDIAL5/MsdialGuiApp/ViewModel/ImagingImms/ImagingImmsMainViewModel.cs
New feature implementation for imaging data management and processing.
This pull request introduces new classes and interfaces to enhance imaging data handling, including the addition of methods for managing regions of interest (ROIs) and updating existing models to support new imaging functionalities. 
- `DimsProviderFactoryParameter.cs`: Introduced new methods in `IDimsDataProviderFactoryParameter` for creating `RawMeasurement` data providers.
- `ImagingDimsImageModel.cs`: New class created to manage imaging data and ROIs.
- `WholeImageResultModel.cs`: Updated to implement `IWholeImageResultModel` and manage intensity images.
- XAML files: Updated to include new UI elements for imaging functionalities, enhancing user interaction.
=> Implement analysis pipeline and UI for TIMS-off imaging
