systemsomicslab/MsdialWorkbench

src/MSDIAL5/MsdialGuiApp/Model/DataObj/StandardCompoundModel.cs
src/MSDIAL5/MsdialGuiApp/Model/Statistics/SplashSetModel.cs

Even spots that were not Ref Matched were used for normalization.

Fix a bug of the SplashSetModel.Find method.

---

src/Common/CommonStandard/DataObj/Property/AdductIon.cs

[M+CH3COO]- and [M+Hac-H]-, [M+HCOO]- and [M+FA-H]- not identified as identical

Fix a bug of AdductType view

---

src/MSDIAL5/MsdialGuiApp/Model/Chart/MsSpectrumModel.cs

Address a bug where the reference spectrum is not displayed for peaks with suggested annotation.

Fix bug: resolve display issue in file specific MS/MS view

---

src/MSDIAL4/MsdialConsoleAppCore/Parser/ConfigParser.cs
src/MSDIAL4/MsdialConsoleAppCore/Process/LcmsDdaProcess.cs
src/MSDIAL4/MsdialConsoleAppCore/Properties/Resources.Designer.cs
src/MSDIAL4/MsdialConsoleAppCore/Properties/Resources.resx

Added support for multiple CPU threads in _lcmsdda_ mode for MsdialConsoleApp, version 4.9.27012024. E.g. use `number of threads:64` in the parameter file to run processing on 64 threads. For efficiency and not to violate job scheduler rules, the actual number of threads is limited to the maximum number of cores available.
Successfully processed both mzML and abf files in positive and negative modes on Windows and linux-x64 versions.

MsdialConsoleApp - added support for multiple CPU threads

---

src/MSDIAL5/MsdialGuiApp/View/Setting/GcmsAlignmentParameterSettingView.xaml

Added an option to the GCMS settings view to use the base peak m/z value as the quant mass.

Add base peak setting option for GCMS

---

src/MSDIAL5/MsdialCore/Export/NistRecordBuilder.cs
tests/MSDIAL5/MsdialCoreTests/Export/NistRecordBuilderTests.cs

Fix bug in MoleculeProperty where null Formula causes errors
- Updated the SetMoleculeProperty method to automatically set the Formula to `string.Empty` if a null value is encountered.
- Added a new test case that specifically passes a null Formula to the method to verify that the issue is resolved and that no errors occur.

Fix Null Formula Handling in MoleculeProperty

---

src/MSDIAL5/MsdialGuiApp/Model/Setting/DatasetFileSettingModel.cs
src/MSDIAL5/MsdialGuiApp/View/Setting/DatasetFileSettingView.xaml
src/MSDIAL5/MsdialGuiApp/View/Setting/DatasetFileSettingView.xaml.cs
src/MSDIAL5/MsdialGuiApp/ViewModel/Setting/DatasetFileSettingViewModel.cs

New feature to enhance file type support messaging in the dataset file settings.
Introduced a mechanism to check file types and display support messages in the UI.
- `DatasetFileSettingModel`: Added `SupportingMessage` property and `FileTypeChecker` class.
- `SetFiles` method: Modified to use `FileTypeChecker` and set `SupportingMessage`.
- `DatasetFileSettingView.xaml`: Updated layout and added `TextBox` for support messages.
- `DatasetFileSettingViewModel`: Added `SupportingMessage` property as a read-only reactive property.

Enhanced File Type Support Messaging in Dataset File Settings

---

src/Common/ChartDrawing/DrawVisual/DrawVisualManualPeakModification.cs

Refactor chromatogram logic and reorganize namespaces
Refactored logic for finding scan IDs in the chromatogram:
- Removed `chromBegin` and `chromTop` variables.
- Used `LowerBound` and `UpperBound` methods to find indices for `left`, `right`, and `top`.
- Simplified loops for finding minimum intensity on left and right sides.
- Set properties `ScanLeft`, `ScanRight`, `ScanTop`, `HeightLeftFromZero`, `HeightRightFromZero`, and `HeightFromZero` directly after loops.
Improved code readability and potentially performance by reducing conditional checks and simplifying loops.

Refactor chromatogram logic and reorganize namespaces

---

src/Common/ChartDrawing/Behavior/AreaSelectBehavior.cs
src/Common/ChartDrawing/Chart/ErrorBar.cs
src/Common/CommonStandard/Extension/IEnumerableExtension.cs
src/MSDIAL5/MsdialCore/Algorithm/Alignment/PeakAligner.cs
src/MSDIAL5/MsdialCore/Algorithm/Alignment/PeakAligner3D.cs
src/MSDIAL5/MsdialCore/Algorithm/PeakSpottingCore.cs
src/MSDIAL5/MsdialGuiApp/View/PeakCuration/AlignedPeakCorrectionWinLegacy.xaml.cs
src/MSDIAL5/MsdialImmsCore/Algorithm/Ms2Dec.cs
src/MSDIAL5/MsdialLcMsApi/Algorithm/Ms2Dec.cs
tests/Common/CommonStandardTests/Algorithm/ChromSmoothing/SmoothingTests.cs
tests/Common/CommonStandardTests/Extension/IEnumerableExtensionTests.cs
tests/Common/CommonStandardTests/Lipidomics/CeramidesSpectrumGeneratorTests.cs
tests/Common/CommonStandardTests/Lipidomics/EtherPCSpectrumGeneratorTests.cs
tests/Common/CommonStandardTests/Lipidomics/EtherPESpectrumGeneratorTests.cs
tests/Common/CommonStandardTests/Lipidomics/HexCerSpectrumGeneratorTests.cs
tests/Common/CommonStandardTests/Lipidomics/LPXSpectrumGeneratorTests.cs
tests/Common/CommonStandardTests/Lipidomics/OadSpectrumPeakGeneratorTests.cs
tests/Common/CommonStandardTests/Lipidomics/Omega3nChainGeneratorTests.cs
tests/Common/CommonStandardTests/Lipidomics/OtherLipidSpectrumGeneratorTests.cs
tests/Common/CommonStandardTests/Lipidomics/PCSpectrumGeneratorTests.cs
tests/Common/CommonStandardTests/Lipidomics/PXSpectrumGeneratorTests.cs
tests/Common/CommonStandardTests/Lipidomics/SpectrumPeakGeneratorTests.cs
tests/Common/CommonStandardTests/Parser/TextLibraryParserTests.cs
tests/Common/CommonStandardTests/Utility/SearchCollectionTest.cs

Code cleanup to maintain compatibility across different .NET versions and optimize performance.
Replaced the `Zip` method with a custom `ZipInternal` method across multiple files to ensure compatibility and performance optimization.
- `IEnumerableExtension.cs`: Introduced `ZipInternal` method with conditional implementation based on the target framework.
- `CompMs.Graphics.Behavior`, `CompMs.Graphics.Chart`, `CompMs.Common.Extension`, `CompMs.MsdialCore.Algorithm`, `CompMs.App.Msdial.View.PeakCuration`: Replaced `Zip` with `ZipInternal`.
- `CompMs.Common.Lipidomics.Tests`: Updated test methods to use `ZipInternal` for pairing elements from two sequences.
- `TextLibraryParserTests.cs` and `SearchCollectionTest.cs`: Replaced `Zip` with `ZipInternal` in multiple foreach loops for element …

Replace `Zip` with `ZipInternal` across codebase

---

src/MSDIAL5/MsdialCore/Algorithm/Internal/PrecursorMzSelectedDataProvider.cs
src/MSDIAL5/MsdialCore/DataObj/DriftTimeTypedSpectra.cs
src/MSDIAL5/MsdialCore/DataObj/RetentionTimeTypedSpectra.cs

Refactor and add null checks in spectra processing
Refactored `PrecursorMzSelectedDataProvider` to use a constructor initializer and introduced a private static method `IsNearBy` to encapsulate m/z tolerance logic. Added null checks for the `Precursor` property in `DriftTimeTypedSpectra` and `RetentionTimeTypedSpectra` to prevent null reference exceptions.

Refactor and add null checks in spectra processing

---

src/MSDIAL5/MsdialCore/Algorithm/PeakSpottingCore.cs
src/MSDIAL5/MsdialCore/MsdialCore.csproj
src/MSDIAL5/MsdialDimsCore/MsdialDimsCore.csproj
src/MSDIAL5/MsdialGcMsApi/MsdialGcMsApi.csproj
src/MSDIAL5/MsdialImmsCore/MsdialImmsCore.csproj
src/MSDIAL5/MsdialImmsImagingCore/MsdialImmsImagingCore.csproj
src/MSDIAL5/MsdialIntegrate/MsdialIntegrate.csproj
src/MSDIAL5/MsdialLcImMsApi/MsdialLcImMsApi.csproj
src/MSDIAL5/MsdialLcMsApi/MsdialLcMsApi.csproj

Add net48 to TargetFrameworks to avoid using netstandard version of Accord
To address the issue in Accord (https://github.com/accord-net/framework/issues/1426),
added net48 to the TargetFrameworks of each project. This ensures that the netstandard
version of Accord is not used.

Add net48 to TargetFrameworks to avoid using netstandard version of Accord

---

src/MSDIAL5/MsdialGuiApp/ViewModel/Export/ProteinGroupExportViewModel.cs

Change Export Executability Property to ReactivePropertySlim in Proteomics
Replaced ReadOnlyReactivePropertySlim with ReactivePropertySlim for controlling export executability in Proteomics. This change ensures the initial state is correctly notified upon subscription, addressing cases where ReadOnlyReactivePropertySlim may not emit the initial value.

Change Export Executability Property to ReactivePropertySlim in Proteomics

---

src/MSDIAL5/MsdialCore/DataObj/MsdialDataStorage.cs
src/MSDIAL5/MsdialCore/DataObj/ProjectDataStorage.cs
src/MSDIAL5/MsdialCore/DataObj/RetentionTimeCorrectionBean.cs

This pull request improves data storage handling and fixes a condition check for retention correction results.
- `MsdialDataStorage.cs`: Initialize `MspDB` as an empty array and manage temporary storage for `Chromatogram` properties.
- `ProjectDataStorage.cs`: Update condition for saving retention correction results to check `rtbean.IsLoaded`.
- `RetentionTimeCorrectionBean.cs`: Add serialization properties, `IsLoaded` property, and adjust `SerializationConstructor` usage.

Code improvement and bug fix.

---

src/Common/ChartDrawing/Behavior/ZoomByDragBehavior.cs

Improve Zoom Responsiveness on Axes with No Direct Drag Influence
Enhanced zoom behavior on graph axes by allowing minimal movement in the non-target direction (e.g., horizontal movement during vertical axis zoom) to trigger zooming. This prevents cases where zoom was not activated due to insufficient drag in the ignored direction.

Improve Zoom Responsiveness on Axes with No Direct Drag Influence

---

src/MSDIAL5/MsdialGuiApp/Model/Chart/AlignmentEicModel.cs
src/MSDIAL5/MsdialGuiApp/Model/Dims/DimsAlignmentModel.cs
src/MSDIAL5/MsdialGuiApp/Model/Gcms/GcmsAlignmentModel.cs
src/MSDIAL5/MsdialGuiApp/Model/Imms/ImmsAlignmentModel.cs
src/MSDIAL5/MsdialGuiApp/Model/Lcimms/LcimmsAlignmentModel.cs
src/MSDIAL5/MsdialGuiApp/Model/Lcms/LcmsAlignmentModel.cs
src/MSDIAL5/MsdialGuiApp/View/PeakCuration/AlignedPeakCorrectionWinLegacy.xaml.cs
src/MSDIAL5/MsdialGuiApp/View/PeakCuration/SampleTableViewerInAlignmentLegacy.xaml.cs

API change to enhance handling of file properties for color and brush mappings.
Added `FilePropertiesModel filePropertiesModel` parameter to constructors and methods to improve dynamic and reactive management of file properties.
- `AlignmentEicModel` constructor and `Create` method updated to include `filePropertiesModel`.
- Updated instantiation in `SampleTableViewerInAlignmentModelLegacy` and `AlignedChromatogramModificationModelLegacy` to pass `filePropertiesModel`.
- Similar updates in `DimsAlignmentModel.cs`, `GcmsAlignmentModel.cs`, `ImmsAlignmentModel.cs`, `LcimmsAlignmentModel.cs`, `LcmsAlignmentModel.cs`.
- `AlignedPeakCorrectionWinLegacy.xaml.cs` updated to include `filePropertiesModel` in constructor and `LoadPeakProperty` method.
- Removed unused `using …

Updated Alignment Chromatogram View to Use Class-Based Colors

---

src/MSDIAL5/MsdialCore/Algorithm/Alignment/IPeakJoiner.cs
src/MSDIAL5/MsdialCore/Algorithm/Alignment/PeakAligner.cs
src/MSDIAL5/MsdialCore/Algorithm/DataAccessor.cs
src/MSDIAL5/MsdialCore/Algorithm/IFeatureAccessor.cs
src/MSDIAL5/MsdialCore/Parameter/ParameterBase.cs
src/MSDIAL5/MsdialGcMsApi/Algorithm/Alignment/GcmsAlignmentProcessFactory.cs
src/MSDIAL5/MsdialGcMsApi/Algorithm/Alignment/GcmsPeakJoiner.cs
src/MSDIAL5/MsdialGcMsApi/Algorithm/GcmsDataAccessor.cs
src/MSDIAL5/MsdialGuiApp/Model/Setting/AlignmentParameterSettingModel.cs
src/MSDIAL5/MsdialGuiApp/Model/Setting/GcmsAlignmentParameterSettingModel.cs
src/MSDIAL5/MsdialGuiApp/View/Setting/AlignmentParameterSettingView.xaml
src/MSDIAL5/MsdialGuiApp/ViewModel/Setting/AlignmentParameterSettingViewModel.cs
src/MSDIAL5/MsdialGuiApp/ViewModel/Setting/GcmsAlignmentParameterSettingViewModel.cs
src/MSDIAL5/MsdialLcMsApi/Algorithm/Alignment/LcmsAlignmentProcessFactory.cs
src/MSDIAL5/MsdialLcMsApi/Algorithm/Alignment/LcmsPeakJoiner.cs
src/MSDIAL5/MsdialLcMsApi/Algorithm/LcmsDataAccessor.cs
tests/MSDIAL5/MsdialLcMsApiTests/Algorithm/Alignment/LcmsPeakJoinerTests.cs
tests/MSDIAL5/MsdialLcMsApiTests/MsdialLcMsApiTests.csproj

Refactoring, new feature, and test enhancements to improve modularity, maintainability, and alignment functionality.  
This PR introduces the `UseRefMatchedPeaksOnly` feature, refactors alignment logic to use modern C# practices, and enhances test coverage with updated data structures.  
- **`IPeakJoiner`, `GcmsPeakJoiner`, and `LcmsPeakJoiner`**: Refactored to use `IFeatureAccessor` for modularity and added support for `UseRefMatchedPeaksOnly`.  
- **`GcmsDataAccessor` and `LcmsDataAccessor`**: Implemented `IFeatureAccessor` and updated methods for better abstraction and readability.  
- **UI and ViewModel**: Added a checkbox and property binding for `UseRefMatchedPeaksOnly` in alignment settings.  
- **Tests**: Updated `LcmsPeakJoinerTests` to use `ChromatogramPeakFeature`, introduced …

Added Option to Perform Alignment Using Only Ref. Matched Peaks

---

src/MSDIAL5/MsdialGuiApp/View/Chart/Ms2ChromatogramsView.xaml
src/MSDIAL5/MsdialGuiApp/View/PeakCuration/SampleTableViewerInAlignmentLegacy.xaml.cs

Code cleanup and UI improvement  
Refactored chart controls and brush mapping logic to improve maintainability, performance, and UI flexibility.  
- **Ms2ChromatogramsView.xaml**: Replaced `MultiChart` with `SimpleChartControl`, updated bindings, styles, and added `ItemsControl` templates for chromatograms.  
- **SampleTableViewerInAlignmentLegacy.xaml.cs**: Simplified brush mapping using `cls2brsh` with `Replay(1).RefCount()` and refactored row generation with `ZipInternal`.  
- Standardized tooltips for `LineChartControl` and `ScatterControlSlim` to a consistent format.

Fixed Bug Where EIC Was Not Displayed After Alignment and Improved Chart UI

---

src/MSDIAL5/MsdialGuiApp/View/Dims/DimsMainView.xaml
src/MSDIAL5/MsdialGuiApp/View/Gcms/GcmsMainView.xaml
src/MSDIAL5/MsdialGuiApp/View/Imms/ImmsMainView.xaml
src/MSDIAL5/MsdialGuiApp/View/Lcimms/LcimmsMainView.xaml
src/MSDIAL5/MsdialGuiApp/View/Lcms/LcmsMainView.xaml

Fix typo in XAML: "Exp. vs.Rep." to "Exp. vs. Ref."
Corrected text in `TextBlock` elements within `DataTemplate`
for `RawDecSpectrumsViewModel` across multiple XAML files
(`DimsMainView.xaml`, `GcmsMainView.xaml`, `ImmsMainView.xaml`,
`LcimmsMainView.xaml`, and `LcmsMainView.xaml`). Ensures
consistency and resolves a typographical error in displayed text.

Fix typo in XAML: "Exp. vs.Rep." to "Exp. vs. Ref."

---

src/Common/ChartDrawing/Behavior/ItemSelectBehavior.cs
src/Common/ChartDrawing/Converter/AreEqualsConverter.cs
src/MSDIAL5/MsdialGuiApp/View/Chart/AlignmentMs2SpectrumView.xaml
src/MSDIAL5/MsdialGuiApp/View/Chart/MsSpectrumView.xaml
src/MSDIAL5/MsdialGuiApp/View/Chart/RawPurifiedView.xaml
tests/Common/ChartDrawingUiTest/Behavior/ItemSelectBehaviorTest.xaml
tests/Common/ChartDrawingUiTest/Behavior/ItemSelectBehaviorTest.xaml.cs
tests/Common/ChartDrawingUiTest/MainWindow.xaml.cs

New feature: Introduced a behavior for item selection in WPF applications.  
Added `ItemSelectBehavior` to standardize item selection handling and updated multiple views to support dynamic axis type selection via context menus.  
- **`ItemSelectBehavior.cs`**: Added a new behavior class with dependency properties and event handlers for selection tracking.  
- **`AreEqualsConverter.cs`**: Enhanced with a static instance for reuse in bindings.  
- **`AlignmentMs2SpectrumView.xaml`, `MsSpectrumView.xaml`, `RawPurifiedView.xaml`**: Integrated `ItemSelectBehavior` and `AreEqualsConverter` for axis type selection via context menus.  
- **`ItemSelectBehaviorTest.xaml` and `ItemSelectBehaviorTest.xaml.cs`**: Added a test page to demonstrate and validate the new behavior.  
- …

Added ItemSelectBehavior Helper for Selecting Specific Elements from Lists

---

src/MSDIAL5/MsdialCore/MSDec/MSDecHandler.cs
src/MSDIAL5/MsdialCore/Parameter/ParameterBase.cs
src/MSDIAL5/MsdialCore/Utility/DataAccess.cs
src/MSDIAL5/MsdialDimsCore/Algorithm/Ms2Dec.cs
src/MSDIAL5/MsdialGuiApp/Model/Setting/DeconvolutionSettingModel.cs
src/MSDIAL5/MsdialGuiApp/Model/Setting/MethodSettingModelFactory.cs
src/MSDIAL5/MsdialGuiApp/View/Setting/DeconvolutionSettingView.xaml
src/MSDIAL5/MsdialGuiApp/ViewModel/DataObj/ParameterBaseVM.cs
src/MSDIAL5/MsdialGuiApp/ViewModel/Setting/DeconvolutionSettingViewModel.cs
src/MSDIAL5/MsdialImmsCore/Algorithm/Ms2Dec.cs
src/MSDIAL5/MsdialLcImMsApi/Algorithm/Ms2Dec.cs
src/MSDIAL5/MsdialLcMsApi/Algorithm/Ms2Dec.cs
tests/MSDIAL5/MsdialCoreTestApp/Parser/ConfigParser.cs

New feature  
Introduces a `RelativeAmplitudeCutoff` parameter for flexible spectrum filtering based on relative intensity thresholds, complementing the existing absolute threshold. Updates span core logic, UI, ViewModel, and configuration parsing for seamless integration.  
- **`MSDecHandler.cs`**: Updated spectrum filtering logic to use both relative and absolute amplitude cutoffs.  
- **`ParameterBase.cs`**: Added `RelativeAmplitudeCutoff` property with default value and updated `ToString` method.  
- **`DeconvolutionSettingView.xaml`**: Added UI input for `RelativeAmplitudeCutoff` with validation and tooltips.  
- **`ConfigParser.cs`**: Enabled parsing of `RelativeAmplitudeCutoff` from configuration files.  
- **`Ms2Dec.cs`**: Enhanced MS/MS spectrum handling to incorporate the new …

Added RelativeAmplitudeCutoff Parameter for Spectrum Filtering in Deconvolution

---

src/Common/CommonStandard/Lipidomics/EieioMsCharacterizationUtility.cs

Handle null or empty exp_spectrum in calculations
Updated the calculation of minimumPeakIntensity to safely handle cases where exp_spectrum may be null or empty. Utilized the null-conditional operator and DefaultIfEmpty() to ensure a default value of 0 is returned, preventing potential exceptions.

Handle null or empty exp_spectrum in calculations
